/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

SET NAMES 'utf8';
USE webshop;

INSERT INTO shop_category VALUES
(2, 'Zubehör', 0, 'Zubehör für echte Gewürzgourmets'),
(4, 'Tee', 0, 'Verschiede Teesorten'),
(100, 'Salz', 1, 'Tafelsalze'),
(101, 'Pfeffer', 1, 'Pfeffersorten'),
(102, 'Exotische Gewürze', 1, 'Exotische Gewürze und Gewürzmischungen');

INSERT INTO shop_item VALUES
(1, 'Tafelsalz', 'http://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Speisesalz.jpg/1280px-Speisesalz.jpg', 'Speisesalz, Kochsalz oder Tafelsalz (umgangssprachlich einfach „Salz") ist das in der Küche für die Ernährung verwendete Salz. Es besteht hauptsächlich Natriumchlorid.', 'Tafelsalz, 1kg Packung', 0.99, 100),
(2, 'Schwarzer Pfeffer', 'https://demoshop.jtl-software.de/bilder/produkte/gross/Schwarzer-Pfeffer.jpg', 'Der Pfefferstrauch (<i>Piper nigrum</i>), auch Schwarzer Pfeffer oder kurz Pfeffer genannt, ist eine Pflanzenart aus der Familie der Pfeffergewächse (Piperaceae). Die Früchte werden wegen des darin enthaltenen Alkaloids als scharf schmeckendes Gewürz verwendet. Zur Unterscheidung von ähnlichen Gewürzen spricht man auch vom echtem Pfeffer.', 'Schwarzer Pfeffer, 50g Packung', 1.29, 101),
(3, 'Oregano', 'http://shop.strato.de/WebRoot/Store/Shops/15435630/4593/AF86/9666/1072/FDFA/C0A8/2836/E5E6/Oregano.jpg', '<h1> Oregano</h1><Br>\r\nOregano (Origanum vulgare) ist eine Pflanzenart in der Familie der Lippenblütler (Lamiaceae). Trivialnamen sind etwa Dorst, Dost, Echter Dost, Gemeiner Dost, Wohlgemut oder Wilder Majoran. Sie wird als Gewürz- und Heilpflanze verwendet.', '50g Dose getrockneter Oregano', 2.99, 102),
(4, 'Grobes Meersalz', 'http://www.pickel-guide.de/bilder/meersalz.jpg', '<H1>500g Grobes französisches Meersalz</h1><br>\r\n<b>Grob in der Struktur – fein im Geschmack</b> <br> \r\nDie Salzkristalle des groben Meersalzes bilden sich in der gesättigten Sole der Salzgärten. Sonne, Wind und Wärme lassen das Wasser verdunsten und die Salzkristalle am Boden der Solebecken wachsen. Von dort werden sie vom Salzbauern mit Hilfe spezieller Salzrechen geerntet. An der Sonne getrocknet entstehen, je nach Farbe des Tons am Boden der Salzbecken, leicht graue bis schneeweiße Kristalle. Das grobe Meersalz eignet sich ideal zum Garen im Salzmantel oder auf dem Salzbett. Beim Würzen von großen Fleisch- oder Fischstücken werden die Vorteile des groben Meersalzes besonders deutlich, da es sich langsamer löst als feines Salz und somit nach und nach in das Bratgut eindringt.\r\n<br><br>\r\n<li>Ohne künstliche Zusatzstoffe wie Glutamat, Geschmacksverstärker, künstliche Farbstoffe, künstliche Aromen, Konservierungsstoffe</li>\r\n<li>Es werden keine Füllstoffe verwendet und es wird kein Salz, Dextrose, Stärke oder Zucker beigemischt</li>\r\n<li>Sämtliche Produkte, aus allen Produktgruppen, sind ungeschwefelt und unbestrahlt. </li>', 'französisches Meersalz, ohne Zusatzstoffe, 500g', 3.49, 100),
(5, '100g grobes hawaiianisches schwarzes Meersalz', 'http://www.orlandosidee.de/bilder/schwarzes-salz.jpg', '<h1>100g grobes hawaiianisches schwarzes Meersalz</h1><br>\r\nDas schwarze Meersalz von der Insel Molokai wir durch ein besonders Verfahren aus dem Pazifik Wasser gewonnen und mit Hochreiner Aktivkohle versetzt. Es hat antitoxische und Verdauungsfördernde Wirkung.', '100g gesundes, grobes und schwarzes Meersalz aus Hawaii.', 4.49, 100),
(6, '50g Ajowan', 'http://upload.wikimedia.org/wikipedia/commons/0/0e/Ajwain.JPG', '<h1>50g Ajowan</h1><br>\r\nDas starke Aroma der Samen wird durch Rösten oder Braten verstärkt und wird in der indischen Küche zum Würzen von Fleisch- und Gemüsegerichten, insbesondere von Linsencurrys (Dals), Suppen und kleineren Teiggerichten verwendet. Das Aroma erinnert an Thymian und ist ausgesprochen intensiv. Daher sollte man mit Ajowan sehr sparsam umgehen. Er verleiht Gerichten eine fruchtige Note.', 'Ajowan ist ein Gewürz der indischen Küche, welches hierzulande noch äußerst unbekannt ist.', 3.89, 102),
(7, '50g Bockshornklee Samen', 'http://www.teesorten-online.com/images/Bockshornkleesamen.jpg', '<h1> 50g Bockshornklee Samen</h1> <BR>\r\nBockshornklee lässt sich in der Küche vielseitig nutzen. Traditionell würtzt Indien mit seinen Samen Curry- und Chutneygerichte, und mit den Blättern werden Fisch oder eingelegtes Gemüse aromatisiert. Gekeimte Samen sind eine willkommene würzige Abwechslung in Salaten.', 'Bockshornklee Samen sind vielseitig in der Küche Nutzbar. z.B. für Salate oder ein indisches Curry.', 2.49, 102),
(8, '50g frische Bockshornklee Blätter', 'http://i00.i.aliimg.com/photo/v12/117283810/Fresh_Fenugreek_Leaf.jpg', '<h1>50g frische Bockschornklee Blätter</h1><br>\r\nBockshornklee lässt sich in der Küche vielseitig nutzen. Traditionell würzt Indien mit seinen Samen Curry- und Chutneygerichte, und mit den Blättern werden Fisch oder eingelegtes Gemüse aromatisiert. Gekeimte Samen sind eine willkommene würzige Abwechslung in Salaten.', 'Frische Bockschornklee Blätter sind perfekt, um einen neuen Geschmack in herkömmliche Salate zu bringen.', 1.99, 102),
(9, '50g Cayennepfeffer ', 'http://i40.twenga.com/essen-und-trinken/cayenne-pfeffer/5-kg-cayenne-pfeffer-tp_1960490411396419050f.jpg', '<h1>50g Cayennepfeffer </h1><br>\r\nCayennepfeffer ist eigentlich kein Pfeffer, sondern Chili. Chili kann frisch oder getrocknet, reif oder unreif, gekocht oder roh verwendet werden. Als Cayennepfeffer wird das blassrote Pulver aus den getrockneten, gemahlenen Früchten bezeichnet.<br><br>\r\n<b>ACHTUNG SCHARF!<b>', 'Der scharfe Pfeffer, der eigentlich kein Pfeffer ist.', 0.99, 101),
(10, '100g Ingwerwurzel', 'http://www.apotheken-umschau.de/multimedia/27/236/121/33906958353.jpg', '<h1>100g Ingwerwurzel</h1> <br>\r\nAls frisches Gewürz passt die Knolle hervorragend zu asiatischen Gerichten und Currys. Ein Tipp von Gesundheitskoch Peter Asch aus Riedering am Chiemsee: Ein Stück frischen Ingwer abschneiden und vor allen anderen Zutaten in heißem öl kurz anbraten. Dann den Ingwer wieder herausnehmen. So bleibt das feine Aroma im Gericht erhalten, es schmeckt aber nicht zu intensiv nach Ingwer.', 'Früher in Indien, China und heute in allen Ländern sehr beliebt!', 0.99, 102),
(11, '363g Teekanne Premium Selection Box', 'http://ecx.images-amazon.com/images/I/71tBo6e56xL._SL1462_.jpg', '<h1> 363g Teekanne Premium Selection Box</h1><br>\r\nPremium Selection Box Geschmacksvielfalt in höchster Qualität, entwickelt für den modernen Genießer. Eine Premium-Klasse, die von feinen Schwarztees über wohltuende Kräutertees bis hin zu frischen Früchtetees reicht. Eine Sortenvielfalt von 12 verschiedenen Tees lässt kaum einen Teetrinker-Wunsch offen. Das TEEKANNE Gastro Premium Sortiment Das ganz besondere Kennzeichen des Sortimentes ist die hochwertige Aroma-Schutz-Umhüllung jedes einzelnen Beutels, die zusätzlich zum optimalen Hygiene-Schutz und zur besten Lagerfähigkeit beiträgt. Inhalt 15x 1,75g English Breakfast, 15 x 1,75g Assam, 15 x 1,75g Darjeeling, 15 x 2,00g Earl Grey, 15 x 1,75g Green Tea, 15 x 1,75g Ingwer Zitrone, 15 x 1,50g Kamille, 15 x 2,00g 8 Kräuter, 15 x 2,25g Pfefferminze, 15 x 1,75g Rooibos Vanilla, 15 x 3,00g Fruit Selection, 15 x 3,00g Waldbeeren.', 'Genießen Sie die Geschmacksvielfalt von Teekanne in einer Box.', 20.99, 4),
(12, '125g Japanischer Sencha Grüntee mit Dose', 'http://ecx.images-amazon.com/images/I/71YxWNdtojL._SL1500_.jpg', '<h1>125g Japanischer Sencha Grüntee mit Dose</h1><BR>\r\nDie japanische Grünteesorte Sencha ist der in Japan mit Abstand am meisten angebaute (etwa 78%) und getrunkene grüne Tee. Gleichzeitig ist er der in westlichen Ländern bekannteste und verbreiteste grüne Tee. „Sen“ hat die japanische Bedeutung von „Aufgiessen / Anbrauen“ mit heissem Wasser und „Cha“ bedeutet Tee. \r\nSie bekommen Sencha Tee in höchster Qualität in einer praktischen Aufbewahrungsbox.', 'Tee ist gesund, besonders der Japanische Sencha!', 13.99, 4),
(13, '250g Früchtetee von Tee-Meyer', 'http://ecx.images-amazon.com/images/I/51D-DoEb3EL.jpg', 'Zutaten: Apfel, Hibiskus, Hagebutte, Holunderbeeren, Weinbeeren (Weinbeeren, pflanzliches öl), Rooibos, Papayastücke (Papaya, Zucker), Ananasstücke (Ananas, Zucker), Minze, Kokosflocken, Kokoschips (Kokosnuss, Kokosöl, Zucker), Bananenchips (Bananenbruch, Kokosöl) Aroma \r\nZubereitungsempfehlung: Immer mit sprudelndem kalkfreiem kochendem Wasser aufgießen. Ziehzeit: 10 Minuten. Menge/Tasse: 1 TL. Nach belieben süßen. Auch kalt ein erfrischendes Getränk.\r\n<br><br>\r\nTee-Meyer steht seid langem für Qualität und Handabgepackte Teevariationen.', 'Der frische Tee mit der Power als vielen Früchten.', 4.25, 4),
(14, 'Rosenstein & Söhne Teekanne aus Glas mit Edelstahl', 'http://ecx.images-amazon.com/images/I/71dQu1wfNVL._SL1300_.jpg', '<h1>Rosenstein & Söhne Teekanne aus Glas mit Edelstahl-Siebeinsatz, 1,5 l</h1><br>\r\nGenießen Sie frisch zubereiteten Tee ohne großen Aufwand. <br>\r\n\r\nAb sofort kann das gute alte Tee-Ei in der Küchenschublade bleiben: Bereiten Sie Tee von nun an besonders schnell und einfach zu.<br>\r\n\r\nFüllen Sie Ihren Lieblingstee in den Siebeinsatz, gießen Sie frisches, kochendes Wasser in die Kanne und lassen Sie den Tee gemäß den Anweisungen ziehen. Der extra-feine Siebeinsatz aus rostfreiem Edelstahl hält auch sehr kleine Teeblätter und Partikel zurück.<br>\r\n\r\nNehmen Sie anschließend das Sieb einfach heraus. Fertig! Schon können Sie ganz in Ruhe eine anregende, heiße Tasse Tee genießen. Auch das Design überzeugt: In der formschönen Glaskanne können Sie den Tee auch gleich servieren. ', 'Praktischer Teebereiter mit herausnehmbarem Siebeinsatz.', 11.9, 2),
(15, 'WMF Salz- und Pfeffermühlen-Set 2-teilig', 'http://ecx.images-amazon.com/images/I/81lVtqrGMgL._SL1500_.jpg', '<h1>WMF Salz- und Pfeffermühlen-Set 2-teilig</h1><br>\r\nDie WMF CERAMILL Mühlen sorgen für mehr Geschmack, und das im Handumdrehen. Viel einfacher als mit Stößel und Mörser mahlen sie so gut wie alles, was zwischen ihr Mahlwerk kommt: Pfeffer und Salz, Chilischoten und Nelken und vor allem getrocknete Kräuter. Beim Mahlen werden die ätherischen öle frei und entwickeln ihr Aroma wie frisch geerntet. Salz lässt sich in der Mühle fein zermahlen wie Mehl. So verbindet es sich besser mit den Zutaten (wie z.B. in Dressings), löst sich schneller auf und man benötigt insgesamt weniger Salz.', 'Qualitätsmühlen von WMF', 39.95, 2),
(16, 'Kesper Mörser mit Schlegel, Granit', 'http://ecx.images-amazon.com/images/I/816U3MRLT7L._SL1500_.jpg', 'Dieser Mörser mit Schlegel ist perfekt zum mörsern von Gewürzen wie z.B. Pfeffer.\r\n', 'Perfekt zum zerkleinern von Gewürzen.', 12.99, 2);

INSERT INTO shop_stock VALUES
(1, 1000),
(2, 1337);

INSERT INTO users VALUES
(1, 'admin', 'admin@admin.com', 2, 'Admin', 'Adminovich', 'Adminstraße, 2', 38110, 'Braunschweig', '1982-02-20'),
(2, 'maxmustermann', 'max.mustermann@gmail.com', 0, 'Max', 'Mustermann', 'Musterstraße 1', 22222, 'Babelsberg', '1990-01-01'),
(3, 'manmustermann', 'manuelamustermann@gmail.com', 0, 'Manuela', 'Mustermann', 'Musterstraße 2', 22222, 'Babelsberg', '2976-01-01');

/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
 


